language: python

python:
  - 2.7

before_install:
  - sudo apt-get install -y python-pip
  - sudo pip install pip --upgrade
  - sudo pip install hash_ring
  - sudo pip install html2text
  - sudo pip install isodate
  - sudo pip install psutil
  - sudo pip install RestrictedPython
  - sudo pip install textblob
  - sudo pip install xattr

install:
  - sudo python setup.py install

before_script:
  - sudo bin/simulator &
  - sleep 5

dist:
  - xenial

script:
  - sudo scripts/test-drivers.sh
