#!/bin/sh
apt-get install -y build-essential
apt-get install -y libopencv-dev
apt-get install -y libsqlite3-dev
apt-get install -y libzbar-dev
apt-get install -y libzmq-dev
apt-get install -y python-all-dev
apt-get install -y python-cffi
apt-get install -y python-dbus
apt-get install -y python-gevent
apt-get install -y python-gi-dev
apt-get install -y python-imaging
apt-get install -y python-numpy
apt-get install -y python-opencv
apt-get install -y python-pil
apt-get install -y python-pip
apt-get install -y python-pygame
apt-get install -y python-zbar
pip install gensim
pip install hash_ring
pip install html2text
pip install isodate
pip install langid
pip install -U nltk
pip install psutil
pip install pycrypto
pip install pypng
pip install pyqrcode
pip install pysqlite
pip install python-rake
pip install pytz
pip install pyzmq
pip install RestrictedPython
pip install stop-words
pip install textblob
pip install wget
pip install xattr
pip install zerorpc
