#!/usr/bin/python

import os
import sys
import argparse
import commands

_name = commands.getoutput('readlink -f %s' % sys.argv[0])
_path = os.path.dirname(_name)
sys.path.append(_path)

from lib.mount import mount
from lib.server import Server

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--server', action='store_true')
    parser.add_argument('-m', '--mount', action='store_true')
    args = parser.parse_args(sys.argv[1:])
    if args.mount:
        mount()
    elif args.server:
        Server().run()
